export const GET_CARDS_REQUEST = 'GET_CARDS_REQUEST'
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS'
export const GET_CARDS_FAIL = 'GET_CARDS_FAIL'

export const GET_TOP_ORDER_REQUEST = 'GET_TOP_ORDER_REQUEST'
export const GET_TOP_ORDER_SUCCESS = 'GET_TOP_ORDER_SUCCESS'
export const GET_TOP_ORDER_FAIL = 'GET_TOP_ORDER_FAIL'

export const GET_LAST_ORDER_REQUEST = 'GET_LAST_ORDER_REQUEST'
export const GET_LAST_ORDER_SUCCESS = 'GET_LAST_ORDER_SUCCESS'
export const GET_LAST_ORDER_FAIL = 'GET_LAST_ORDER_FAIL'
